{
    'name': 'Construction Costing Application',
    'version': '18.0.3.4.3',
    'category': 'Construction',
    'summary': 'Costing management application for construction projects',
    'author': 'Dekad (Mofeed Dozkanji)',
    'depends': [
        'base',
        'mail',
        'crm',
        'project',
        'sale',
        'purchase',
        'analytic',
        'account',
        'hr',
        'hr_contract',
        'account_asset',
        'stock',
        'purchase_stock',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/job_cost_project_security.xml',
        'views/res_config_settings_views.xml',
        'data/logging_sequence.xml',
        'data/project_sequence.xml',
        'data/job_cost_sheet_sequence.xml',
        'data/job_cost_project_sequence.xml',
        'data/res_partner_category_data.xml',
        'views/crm_lead_views.xml',
        'views/crm_lead_requirements_views.xml',
        'views/job_cost_project_views.xml',
        'views/job_cost_sheet_views.xml',
        'views/labor_tag_views.xml',
        'views/overhead_tag_views.xml',
        'views/construction_log_views.xml',
        'views/project_milestone_views.xml',
        'views/project_update_views.xml',
        'views/purchase_order_line_views.xml',
        'views/purchase_report_views.xml',
        'views/sale_order_views.xml',
        'views/account_move_views.xml',
        'views/hr_expense_views.xml',
        'views/report_wizard_views.xml',
        'views/account_move_line_report_views.xml',
        'views/stock_picking_views.xml',
        'report/account_move_line_report_templates.xml',
        'views/job_cost_dashboard_views.xml',
        'views/menus.xml',
    ],
    'sequence': 1,
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}