from . import bag_type
from . import bag_weight
from . import hotel_room_detail
from . import transportation_location
from . import tours
from . import tour_hotel_details
from . import sale_order_line
from . import purchase_order
from . import product_product
from . import sale_order
from . import res_partner
from . import ticket_passenger