from . import ir_module
from . import product_template
from . import whatsapp_template
from . import res_partner
from . import res_company
from . import base
from . import company_attachment
from . import dynamic_mixin
from . import required_field_config
from . import product_template_attribute_line
from . import product_product
from . import base_document_layout