from . import building
from . import meters
from . import meter_reading
from . import analytic_account
from . import sale_order
from . import property_rental_event
from . import res_partner
from . import account_payment
from . import res_config_settings
from . import product_template
from . import sale_order_line
from . import contract_report
from . import account_payment_method
from . import pdc_wizard
from . import availability_report
from . import building_statement_line
