{
    'name': 'Dekad Material Request',
    'version': '18.0.1.1.1',
    'category': 'Inventory',
    'summary': 'General Material Request for all departments and projects',
    'author': 'Dekad',
    'depends': [
        'base',
        'mail',
        'product',
        'purchase',
        'account',
        'analytic',
        'project',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'wizard/gmr_add_products_wizard_views.xml',
        'views/gmr_request_views.xml',
        'views/purchase_order_views.xml',
        'views/account_move_views.xml',
        'views/res_config_settings_views.xml',
        'views/menu_views.xml',
        'views/project_project_views.xml',
        'views/project_embedded_actions.xml',
        'wizard/gmr_create_po_wizard_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}