from . import academic_term
from . import academic_year
from . import student
from . import subject
from . import grade
from . import teacher
from . import holiday
from . import res_users
from . import religion