from . import res_config_settings
from . import fcm_addon_preference
from . import fcm_device
from . import fcm_notification
from . import mail_thread
from . import mail_message
from . import mail_activity
from . import sale_order
from . import purchase_order
from . import account_move
from . import stock_picking
from . import crm_lead
from . import res_users
