from . import res_partner
from . import sale_order
from . import crm_lead
from . import stock_picking
from . import account_move
from . import crm_stage
from . import res_users
from . import res_config_settings
from . import product_template
