from odoo import models, fields, api, _
from odoo.exceptions import UserError, ValidationError


class JobCostProject(models.Model):
    _name = "job.cost.project"
    _description = "Job Cost Project Card"
    _order = "create_date desc"
    _inherit = ['mail.thread', 'mail.activity.mixin']

    name = fields.Char(string="Project Name", required=True, tracking=True)

    sequence = fields.Char(
        string="Reference",
        readonly=True,
        copy=False,
        default=lambda self: self.env['ir.sequence'].next_by_code('job.cost.project.seq')
    )

    project_type = fields.Selection([
        ('in_house', 'In-House'),
        ('client_contract', 'Client Contract')
    ], string="Project Type", readonly=True)

    company_id = fields.Many2one(
        'res.company',
        string='Company',
        required=True,
        default=lambda self: self.env.company,
        index=True
    )

    creation_date = fields.Date(
        string="Creation Date",
        default=fields.Date.context_today,
        readonly=True,
        tracking=True
    )
    lead_id = fields.Many2one('crm.lead', string="Lead", ondelete='cascade', required=False)
    partner_id = fields.Many2one(
        'res.partner',
        string="Customer",
        related="lead_id.partner_id",
        store=True,
        readonly=False,
        required=True,
        tracking=True
    )
    employee_id = fields.Many2one(
        'hr.employee',
        string="Responsible (HR)",
        required=True,
        tracking=True,
        default=lambda self: self.env.user.employee_id
    )
    analytic_account_id = fields.Many2one('account.analytic.account', string="Analytic Account", readonly=True)

    has_confirmed_so = fields.Boolean(
        compute="_compute_has_confirmed_so",
        store=True,
        string="Has Confirmed Sale Order"
    )

    # Reverse relation to find all quotes generated by this project card
    sale_order_ids = fields.One2many(
        'sale.order',
        'job_cost_project_id',
        string="Linked Quotations"
    )

    # New field to hold the numerical value inside our statinfo block
    quotation_count = fields.Integer(
        string="Quotation Count",
        compute="_compute_quotation_count"
    )

    @api.depends('sale_order_ids')
    def _compute_quotation_count(self):
        """Calculates the total volume of quotations attached to this JCP."""
        for project in self:
            project.quotation_count = len(project.sale_order_ids)

    state = fields.Selection([
        ('draft', 'Draft'),
        ('costing', 'Costing'),
        ('priced', 'Priced'),
        ('so_created', 'Sales Order Created'),
        ('project_created', 'Project Created'),
    ], default="draft", tracking=True)

    currency_id = fields.Many2one(
        'res.currency',
        string='Currency',
        default=lambda self: self.env.company.currency_id,
        required=True
    )

    project_id = fields.Many2one('project.project', string="Project", readonly=True)
    lead_deadline = fields.Date(string="Deadline", related="lead_id.construction_deadline", store=True, readonly=True)
    job_cost_sheet_ids = fields.One2many('job.cost.sheet', 'job_cost_project_id', string="Job Cost Sheets")

    # Cost summary / Pricing definitions
    material_cost = fields.Float(compute="_compute_cost_and_pricing", store=True)
    equipment_cost = fields.Float(compute="_compute_cost_and_pricing", store=True)
    labor_cost = fields.Float(compute="_compute_cost_and_pricing", store=True)
    overhead_cost = fields.Float(compute="_compute_cost_and_pricing", store=True)
    subcontractor_cost = fields.Float(compute="_compute_cost_and_pricing", store=True)
    base_cost_total = fields.Float(string="Base Cost Total", compute="_compute_cost_and_pricing", store=True)
    risk_percent = fields.Float(default=0.0)
    risk_amount = fields.Float(compute="_compute_cost_and_pricing", store=True)
    margin_percent = fields.Float(default=0.0)
    margin_amount = fields.Float(compute="_compute_cost_and_pricing", store=True)
    final_selling_price = fields.Float(string="Final Selling Price", compute="_compute_cost_and_pricing", store=True)

    # FIXED: Expanded dependencies to look into line changes and flipped store=True
    @api.depends(
        'job_cost_sheet_ids.material_total',
        'job_cost_sheet_ids.equipment_total',
        'job_cost_sheet_ids.labor_total',
        'job_cost_sheet_ids.overhead_total',
        'job_cost_sheet_ids.subcontractor_total',
        'risk_percent',
        'margin_percent'
    )
    def _compute_cost_and_pricing(self):
        for pkg in self:
            sheets = pkg.job_cost_sheet_ids
            pkg.material_cost = sum(sheets.mapped("material_total"))
            pkg.equipment_cost = sum(sheets.mapped("equipment_total"))
            pkg.labor_cost = sum(sheets.mapped("labor_total"))
            pkg.overhead_cost = sum(sheets.mapped("overhead_total"))
            pkg.subcontractor_cost = sum(sheets.mapped("subcontractor_total"))

            pkg.base_cost_total = (pkg.material_cost + pkg.equipment_cost +
                                   pkg.labor_cost + pkg.overhead_cost +
                                   pkg.subcontractor_cost)

            pkg.risk_amount = pkg.base_cost_total * (pkg.risk_percent / 100)
            subtotal = pkg.base_cost_total + pkg.risk_amount

            pkg.margin_amount = subtotal * (pkg.margin_percent / 100)
            pkg.final_selling_price = subtotal + pkg.margin_amount

    # -----------------------------------------------------
    # Control the deletion of JCP
    # -----------------------------------------------------

    def unlink(self):
        for project in self:
            # Find all CRM leads pointing to the projects being deleted
            leads = self.env['crm.lead'].search([('job_cost_project_id', 'in', self.ids)])

            # Check if any underlying Job Cost Sheet has reached the 'done' state
            done_sheets = project.job_cost_sheet_ids.filtered(lambda s: s.state == 'done')

            if done_sheets:
                raise UserError(_(
                    "Security Restriction: The Job Cost Project '%s' cannot be deleted "
                    "because it contains %s Job Cost Sheet(s) already marked as 'Done'. "
                    "Consider archiving the project instead to maintain financial records."
                ) % (project.display_name, len(done_sheets)))

            if leads:
                # 1. Reset state to 'draft' so fields become editable again
                leads.write({'requirement_state': 'draft'})

                # 2. Log a clean notice to the chatter so users know why it unlocked
                for lead in leads:
                    lead.message_post(body=_(
                        "ℹ The associated Job Cost Project was deleted. "
                        "Client Requirements have been unlocked and reset to Draft status."
                    ))

                    # 3. Optional: Create an entry in your custom construction log
                    self.env['construction.log'].create_log(
                        description=f"Job cost project for lead '{lead.name}' was deleted. Client requirements reset to draft.",
                        model_name='crm.lead',
                        record=lead,
                        log_type='action',
                    )

        return super(JobCostProject, self).unlink()

    # -----------------------------------------------------
    # Sale Order Relation Logic
    # -----------------------------------------------------

    @api.depends('sale_order_ids.state')
    def _compute_has_confirmed_so(self):
        """
        Computes whether any quotation attached to this JCP has been confirmed.
        If a confirmed order is found, it automatically advances the JCP state.
        """
        for rec in self:
            confirmed_orders = rec.sale_order_ids.filtered(lambda so: so.state == 'sale')
            if confirmed_orders:
                rec.has_confirmed_so = True
                # CRITICAL REQUIREMENT: Automatically push the state forward
                if rec.state == 'priced':
                    rec.state = 'so_created'
            else:
                rec.has_confirmed_so = False

    # -----------------------------------------------------
    # Workflow Logic Buttons & Constraints
    # -----------------------------------------------------

    def action_confirm(self):
        """Advances project layout from Draft to Costing execution stage."""
        for rec in self:
            rec.write({'state': 'costing'})

    def action_approve(self):
        """
        CRITICAL REQUIREMENT: Validates that all associated sub-sheets
        are marked as 'done' before allowing the JCP to advance past 'costing'.
        """
        for rec in self:
            if not rec.job_cost_sheet_ids:
                raise UserError(_("You cannot approve a project without any Job Cost Sheets assigned."))

            incomplete_sheets = rec.job_cost_sheet_ids.filtered(lambda s: s.state != 'done')
            if incomplete_sheets:
                sheet_names = ", ".join([f"'{s.name}'" for s in incomplete_sheets[:5]])
                remaining_count = len(incomplete_sheets) - 5
                tail = f" ...and {remaining_count} more" if remaining_count > 0 else ""

                raise UserError(_(
                    "Action Blocked! You cannot approve this Project until all sub-sheets are completed.\n\n"
                    "Please check the following incomplete sheets: %s%s"
                ) % (sheet_names, tail))

            rec.write({'state': 'priced'})

    def action_return_to_draft(self):
        """ADDED: Resets the state of the project layout back to Draft mode."""
        for rec in self:
            if rec.state in ['so_created', 'project_created']:
                raise UserError(
                    _("Cannot return to draft once business sales documents or operation workflows are built."))
            rec.write({'state': 'draft'})

    def action_create_quotation(self):
        """
        Instantiates an empty, fresh draft quotation page while cleanly injection-mapping
        the current job costing parent link context directly into the new partner view target.
        """
        self.ensure_one()

        # Build context parameters to pre-fill elements on the blank quotation record
        ctx = {
            'default_job_cost_project_id': self.id,
            # If your project model already holds a partner_id link, pass it down seamlessly:
            'default_partner_id': self.partner_id.id if hasattr(self, 'partner_id') and self.partner_id else False,
        }

        return {
            'name': 'Create Quotation',
            'type': 'ir.actions.act_window',
            'res_model': 'sale.order',
            'view_mode': 'form',
            'target': 'current',
            'context': ctx,
        }

    @api.constrains('job_cost_sheet_ids')
    def _check_sheets_state_constraints(self):
        """
        CRITICAL REQUIREMENT: Enforces that sheets can only be added, modified,
        or linked if the JCP record is in the 'costing' state.
        """
        for rec in self:
            # Skip validation during target data generation context paths
            if rec.state != 'costing' and rec.id and not isinstance(rec.id, models.NewId):
                # Ensure the constraint allows removing sheets during back-to-draft adjustments cleanly
                raise ValidationError(_(
                    "Operational Halt! You cannot manage Job Cost Sheets unless the project state is actively set to 'Costing'."
                ))

    def action_reset_to_priced(self):
        """
        Reverts the project state back to 'priced'.
        Blocks validation if there is an active confirmed/done downstream sales contract.
        """
        self.ensure_one()

        # Look for any active confirmed sale orders that are NOT canceled
        active_so = self.sale_order_ids.filtered(lambda s: s.state in ['sale', 'done'])

        if active_so:
            raise UserError(_(
                "Operational Halt! You cannot reset this project to 'Priced' because "
                "there is an active, confirmed Sale Order linked to it (%s). "
                "You must cancel the Sale Order first."
            ) % ", ".join(active_so.mapped('name')))

        # Force state update and trigger dependency recomputations
        self.write({'state': 'priced'})
        self._compute_has_confirmed_so()

    # -----------------------------------------------------
    # Project & Logistics Generation Hooks
    # -----------------------------------------------------

    def action_create_project(self):
        for project_card in self:
            if project_card.project_id:
                raise UserError(_("A project has already been created for this Job Cost Project."))

            # Default to the current logged-in user if no employee is assigned
            project_manager_id = self.env.user.id

            if project_card.employee_id:
                if project_card.employee_id.user_id:
                    # Map directly to the HR Employee's linked User record
                    project_manager_id = project_card.employee_id.user_id.id

            # Create the project mapped to the macro JCP scheduling timeline bounds
            project = self.env['project.project'].create({
                'name': project_card.name,
                'partner_id': project_card.partner_id.id,
                'user_id': project_manager_id,
                'date_start': project_card.creation_date,  # Clamped to creation window
                'date': project_card.lead_deadline,  # Clamped to client deadline
                'allow_billable': True,  # Enables the "Billable" setting by default under Sales & Invoicing
            })

            project_card.project_id = project.id
            project_card.state = 'project_created'

            Milestone = self.env["project.milestone"]
            Task = self.env['project.task']

            for sheet in project_card.job_cost_sheet_ids:
                # Note: No manual date verification loops are needed here anymore.
                # The @api.constrains in job_cost_sheet.py guarantees these values are safe.
                milestone = Milestone.create({
                    "name": sheet.name or _("Milestone"),
                    "project_id": project.id,
                    "deadline": sheet.date_end or project_card.lead_deadline,
                    "contribution": sheet.percentage or 0,
                })

                task_user_ids = False
                if sheet.employee_id and sheet.employee_id.user_id:
                    task_user_ids = [(4, sheet.employee_id.user_id.id)]

                subcontractor_partner_id = False
                subcontractor_subtotal = 0.0
                # >>> NEW: retention %, copied the same way as the two lines above
                subcontractor_retention_percent = 0.0

                if sheet.subcontractor_ids:
                    # Safely grab the single subcontractor line we restricted earlier
                    subcontractor = sheet.subcontractor_ids[0]
                    subcontractor_partner_id = subcontractor.partner_id.id
                    subcontractor_subtotal = subcontractor.cost_price_subtotal
                    subcontractor_retention_percent = subcontractor.retention_percent  # >>> NEW

                task = Task.create({
                    'name': sheet.name,
                    'project_id': project.id,
                    'partner_id': sheet.partner_id.id,
                    'description': sheet.requirement_note,
                    'user_ids': task_user_ids,
                    'sequence': sheet.sequence,
                    'date_deadline': sheet.date_end or False,
                    'planned_start_date': sheet.date_start,
                    'planned_end_date': sheet.date_end,
                    'planned_duration': sheet.boq_expected_duration_days or 0.0,
                    'estimated_cost_total': sheet.final_selling_price,
                    'milestone_id': milestone.id,
                    'subcontractor_partner_id': subcontractor_partner_id,
                    'subcontractor_subtotal': subcontractor_subtotal,
                    'subcontractor_retention_percent': subcontractor_retention_percent,  # >>> NEW
                })
                milestone.related_task_id = task.id

            project_card.message_post(body=_(
                "A Project has been successfully created with %s milestones and tasks "
                "conforming to the JCP operational window (%s to %s)."
            ) % (len(project_card.job_cost_sheet_ids), project_card.creation_date, project_card.lead_deadline))

        return True

    # -------------------------------------------------------------------------
    # SMART BUTTON WINDOW ACTIONS
    # -------------------------------------------------------------------------
    def action_open_quotations(self):
        """Opens a list view filtered to show all draft/sent/confirmed orders for this JCP."""
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'name': 'Quotations',
            'res_model': 'sale.order',
            'view_mode': 'list,form',
            'domain': [('job_cost_project_id', '=', self.id)],
            'context': {'default_job_cost_project_id': self.id},
            'target': 'current',
        }

    def action_open_confirmed_sale_order(self):
        """Directly pulls up the specific primary confirmed Sale Order form view."""
        self.ensure_one()
        # Filter down to extract the target active execution order record row
        confirmed_so = self.sale_order_ids.filtered(lambda s: s.state in ['sale', 'done'])

        if confirmed_so:
            return {
                'type': 'ir.actions.act_window',
                'name': 'Sales Order',
                'res_model': 'sale.order',
                'view_mode': 'form',
                'res_id': confirmed_so[0].id,  # Safely grab the primary confirmation record ID
                'target': 'current',
            }

    def action_open_project(self):
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'name': 'Project',
            'res_model': 'project.project',
            'view_mode': 'form',
            'res_id': self.project_id.id,
            'target': 'current',
        }